package id.lariss.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BoxContentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoxContentAllPropertiesEquals(BoxContent expected, BoxContent actual) {
        assertBoxContentAutoGeneratedPropertiesEquals(expected, actual);
        assertBoxContentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoxContentAllUpdatablePropertiesEquals(BoxContent expected, BoxContent actual) {
        assertBoxContentUpdatableFieldsEquals(expected, actual);
        assertBoxContentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoxContentAutoGeneratedPropertiesEquals(BoxContent expected, BoxContent actual) {
        assertThat(expected)
            .as("Verify BoxContent auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoxContentUpdatableFieldsEquals(BoxContent expected, BoxContent actual) {
        assertThat(expected)
            .as("Verify BoxContent relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getContentEn()).as("check contentEn").isEqualTo(actual.getContentEn()))
            .satisfies(e -> assertThat(e.getContentId()).as("check contentId").isEqualTo(actual.getContentId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoxContentUpdatableRelationshipsEquals(BoxContent expected, BoxContent actual) {
        // empty method
    }
}
