package id.lariss.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MemoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemoryAllPropertiesEquals(Memory expected, Memory actual) {
        assertMemoryAutoGeneratedPropertiesEquals(expected, actual);
        assertMemoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemoryAllUpdatablePropertiesEquals(Memory expected, Memory actual) {
        assertMemoryUpdatableFieldsEquals(expected, actual);
        assertMemoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemoryAutoGeneratedPropertiesEquals(Memory expected, Memory actual) {
        assertThat(expected)
            .as("Verify Memory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemoryUpdatableFieldsEquals(Memory expected, Memory actual) {
        assertThat(expected)
            .as("Verify Memory relevant properties")
            .satisfies(e -> assertThat(e.getAttributeLabel()).as("check attributeLabel").isEqualTo(actual.getAttributeLabel()))
            .satisfies(e -> assertThat(e.getAttributeName()).as("check attributeName").isEqualTo(actual.getAttributeName()))
            .satisfies(e -> assertThat(e.getOptionLabel()).as("check optionLabel").isEqualTo(actual.getOptionLabel()))
            .satisfies(e -> assertThat(e.getOptionValue()).as("check optionValue").isEqualTo(actual.getOptionValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemoryUpdatableRelationshipsEquals(Memory expected, Memory actual) {
        // empty method
    }
}
